-- Student ID: 30632714
-- Student Name: Abhiram Aroop

-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-25 12:47:47 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE drug (
    drug_id               NUMBER(7) NOT NULL,
    drug_name             VARCHAR2(50 BYTE) NOT NULL,
    drug_qty              NUMBER(7) NOT NULL,
    drug_cost             NUMBER(7) NOT NULL,
    visit_visit_datetime  DATE NOT NULL,
    vet_vet_id            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'unique drug identifier';

COMMENT ON COLUMN drug.drug_name IS
    'name of drug';

COMMENT ON COLUMN drug.drug_qty IS
    'Quantity of drug';

COMMENT ON COLUMN drug.drug_cost IS
    'cost of the drug';

COMMENT ON COLUMN drug.visit_visit_datetime IS
    'date and time of visit';

COMMENT ON COLUMN drug.vet_vet_id IS
    'unique identifier for the vet';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id        NUMBER(7) NOT NULL,
    owner_gname     VARCHAR2(50 CHAR) NOT NULL,
    owner_fname     VARCHAR2(50 CHAR) NOT NULL,
    owner_street    VARCHAR2(50 CHAR) NOT NULL,
    owner_town      CHAR(50 CHAR) NOT NULL,
    owner_postcode  NUMBER(7) NOT NULL,
    vet_vet_id      NUMBER(7)
);

COMMENT ON COLUMN owner.owner_id IS
    'Unique identifier for the pet owner';

COMMENT ON COLUMN owner.owner_gname IS
    'Given/First name of the owner';

COMMENT ON COLUMN owner.owner_fname IS
    'family/last name of the owner';

COMMENT ON COLUMN owner.owner_street IS
    'Street where owner lives';

COMMENT ON COLUMN owner.owner_town IS
    'Town where owner is located';

COMMENT ON COLUMN owner.owner_postcode IS
    'Post code of owner''s location';

COMMENT ON COLUMN owner.vet_vet_id IS
    'unique identifier for the vet';

CREATE UNIQUE INDEX owner__idx ON
    owner (
        vet_vet_id
    ASC );

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet (
    pet_id          NUMBER(7) NOT NULL,
    owner_owner_id  NUMBER(7) NOT NULL,
    pet_gender      CHAR(50 CHAR) NOT NULL,
    pet_name        VARCHAR2(50 CHAR) NOT NULL,
    pet_type        VARCHAR2(50 CHAR) NOT NULL,
    pet_dob         DATE NOT NULL,
    pet_deceased    CHAR(1 CHAR) NOT NULL
);

COMMENT ON COLUMN pet.pet_id IS
    'The unique identifier for the pet';

COMMENT ON COLUMN pet.owner_owner_id IS
    'Unique identifier for the pet owner';

COMMENT ON COLUMN pet.pet_gender IS
    'Gender of the animal';

COMMENT ON COLUMN pet.pet_name IS
    'Name of the animal';

COMMENT ON COLUMN pet.pet_type IS
    'Species of animal';

COMMENT ON COLUMN pet.pet_dob IS
    'date of birth of pet';

COMMENT ON COLUMN pet.pet_deceased IS
    'Boolean of whether pet has been deceased';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE service (
    service_code          NUMBER(7) NOT NULL,
    service_desc          VARCHAR2(100 CHAR) NOT NULL,
    service_cost          NUMBER(7) NOT NULL,
    visit_visit_datetime  DATE NOT NULL,
    vet_vet_id            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'unique service identifier';

COMMENT ON COLUMN service.service_desc IS
    'description of service';

COMMENT ON COLUMN service.visit_visit_datetime IS
    'date and time of visit';

COMMENT ON COLUMN service.vet_vet_id IS
    'unique identifier for the vet';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE vet (
    vet_id    NUMBER(7) NOT NULL,
    vet_name  VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN vet.vet_id IS
    'unique identifier for the vet';

COMMENT ON COLUMN vet.vet_name IS
    'name of the vet';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    pet_pet_id      NUMBER(7) NOT NULL,
    visit_datetime  DATE NOT NULL,
    total_cost      NUMBER(7),
    payment_method  CHAR(4 CHAR),
    vet_vet_id      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN visit.pet_pet_id IS
    'The unique identifier for the pet';

COMMENT ON COLUMN visit.visit_datetime IS
    'date and time of visit';

COMMENT ON COLUMN visit.total_cost IS
    'cost of services in visit';

COMMENT ON COLUMN visit.payment_method IS
    'Method of payment of total amount';

COMMENT ON COLUMN visit.vet_vet_id IS
    'unique identifier for the vet';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_datetime,
                                                        vet_vet_id );

ALTER TABLE pet
    ADD CONSTRAINT pet_ownership FOREIGN KEY ( owner_owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE owner
    ADD CONSTRAINT preffered_vet FOREIGN KEY ( vet_vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE drug
    ADD CONSTRAINT visit_drug FOREIGN KEY ( visit_visit_datetime,
                                            vet_vet_id )
        REFERENCES visit ( visit_datetime,
                           vet_vet_id );

ALTER TABLE service
    ADD CONSTRAINT visit_service FOREIGN KEY ( visit_visit_datetime,
                                               vet_vet_id )
        REFERENCES visit ( visit_datetime,
                           vet_vet_id );

CREATE OR REPLACE TRIGGER fkntm_service BEFORE
    UPDATE OF visit_visit_datetime, vet_vet_id ON service
BEGIN
    raise_application_error(-20225,
                           'Non Transferable FK constraint  on table SERVICE is violated');
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
