@@ad_logical\Relational_1\Oracle_Database_12c\DropStatements.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Structure_Type\MDSYS.SDO_GEOMETRY.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Structure_Type\XMLTYPE.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\DRUG.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\DRUG_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\OWNER.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\OWNER_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\PET.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\PET_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\SERVICE.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\SERVICE_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\VET.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\VET_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\VISIT.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\Table\VISIT_Constraints.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\PET_OWNERSHIP.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\PET_VISIT.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\PREFFERED_VET.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\VET_VISIT.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\VISIT_DRUG.sql
@@ad_logical\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\VISIT_SERVICE.sql
