DROP TABLE drug CASCADE CONSTRAINTS;
DROP TABLE owner CASCADE CONSTRAINTS;
DROP TABLE pet CASCADE CONSTRAINTS;
DROP TABLE service CASCADE CONSTRAINTS;
DROP TABLE vet CASCADE CONSTRAINTS;
DROP TABLE visit CASCADE CONSTRAINTS;
